config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name , presence: true , length: {minimum: 3, maximum: 30}
  validates :last_name , presence: true , length: {minimum: 3, maximum: 50}
  validates :email , presence: true , length: {minimum: 10, maximum: 70}  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    def index
        @users = User.all
    end
   
    def new
        @user = User.new
    end
    
    
      def create
       # render plain: params[:user].inspect
        @user = User.new(user_params)
        @user.save
        
        if @user.save
            flash[:notice] = "The user was successfully created"
            redirect_to user_path(@user)
        else
           render 'new' 
       end
        
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    
    def edit 
        @user =User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "User information was successfully updated"
        redirect_to user_path(@user)
        else
          render 'edit'
        end
        
    end 
    
      
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:notice] = "User was successfully deleted"
        redirect_to users_path
        
    end
    
    
    private
    def user_params
        params.require(:user).permit(:first_name,:last_name,:email)
    end
    
    
end

app/controllers/welcome_controller.rb
 class WelcomeController < ApplicationController
     
     def home
         
     end
     
     def new
         
     end
 
     
     
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
   <ul>
     <li><%= msg %></li>
   </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/messages'%>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
 <h1>Create user</h1>
 
 <% if @user.errors.any? %>
 <h2>The following errors prevented the user to getting created</h2>
 <ul>
 <% @user.errors.full_messages.each do |msg|%>
 <li><%= msg %></li> 
 <% end %>
 </ul>
 <% end %>
 
 <%= form_for @user do |f| %>
 
 <p>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name%>
 </p>
 <p>
  <%= f.label :last_name%></br>
  <%= f.text_field :last_name%>
 </p>
 <p>
  <%= f.label :email%><br>
  <%= f.text_area :email%>
 </p>
 
 
 <%= f.submit%>
 <% end %>
 
 <%= link_to 'Back to users listing ', users_path%>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1>Listing all user</h1>
<p>
<%= link_to 'Create new user', new_user_path%>
</p>
<table>
    <tr>
        <th>Name</th>
        <th>Last name</th>
        <th>Email</th>
    </tr>
    <% @users.each do |user|%>
    <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        
        <td><%= link_to'Edit', edit_user_path(user) %></td>
        <td><%= link_to'Show', user_path(user)%></td>
        <td><%= link_to'Delete', user_path(user), method: :delete , data: {confirm: "Are you sure ?" }%></td>
    </tr>
    
    <% end %>
</table>

app/views/users/new.html.erb
 <h1>Create user</h1>
 <%= render 'form'%>

app/views/users/show.html.erb
<h1>Showing selected user</h1>
<p>
    Name: <%=@user.first_name%>
</p>
<p>
    Last name: <%=@user.last_name%>
</p>
<p>
   Email: <%=@user.email%>
</p>
 <%= link_to 'Edit this user ', edit_user_path(@user)%> |
 <%= link_to 'Back to users listing ', users_path%>

app/views/welcome/home.html.erb
<h1>ESTA ES LA PAGINA HOME</h1>

app/views/welcome/new.html.erb
<h1>ESTA ES LA PAGINA NUEVO</h1>
<%= link_to 'Home' , root_path %>